package org.integrallis.drools.loans.domain

rule "ACME-Fico"
	when
	    Mortgage(lender:lenderName == "ACME Mortgage",product:mortgageName)
		application:LoanApplication( lenders contains lender, ficoScore<680 ) 
	then
		application.addMessage(MessageCatalog.MSG_ACME_FICO_680);
end

rule "ACME-Principal"
	when
		mortgage:Mortgage(lender:lenderName == "ACME Mortgage",product:mortgageName)
		application:LoanApplication(lenders contains lender, principal<50000)
	then
		application.addMessage(MessageCatalog.MSG_ACME_PRINCIPAL_50K);
end

rule "ACME-NumberOfUnits"
	when
		mortgage:Mortgage(lender:lenderName == "ACME Mortgage",product:mortgageName)
		application:LoanApplication(lenders contains lender, numberOfUnits>4)	
	then
		application.addMessage(MessageCatalog.MSG_ACME_4_UNIT_MAX);
end

rule "ACME-OneUnitPrincipal"
	when
		mortgage:Mortgage(lender:lenderName == "ACME Mortgage",product:mortgageName)
		application:LoanApplication(lenders contains lender, numberOfUnits==1, principal>=203150)	
	then
		application.addMessage(MessageCatalog.MSG_ACME_1_UNIT_PRINCIPAL);
end

rule "ACME-PrincipalMultipleOf50"
	when
		mortgage:Mortgage(lender:lenderName == "ACME Mortgage",product:mortgageName)
		application:LoanApplication(lenders contains lender, principal % 50 != 0)	
	then
		application.addMessage(MessageCatalog.MSG_ACME_MULT_OF_50_PRINCIPAL);
end

